<?php
  
  function hook_user_node_user_login($account) {
    $current_user = \Drupal::currentUser();
    $user = $current_user->getRoles();
    $o = sizeof($user);
    for($i = 0; $i <= $o - 1; $i++){
      echo("<script>console.log('si junchon por $i vez');</script>");
      echo("<script>console.log('$user[$i]');</script>");
      if ($user[$i] == "project_owner"){
        $roleProject = 1;
      }
    }
    
    if($field_login_count == 0){
      $field_login_count = 1;
      $first_node = 1;
    }

    if($roleProject == 1 && $first_node == 1){
      echo("<script>console.log('si es project owner');</script>");
      \Drupal\node\Entity\Node::create([
        'type' => 'webform',
        'title' => 'First node for user #' . $current_user->id(),
        'uid' => $current_user->id(),
      ])->save();
    }
  }
